SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

SportsStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using System.Collections.Generic;
using System.Linq;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepository repository;
        public NavigationMenuViewComponent(IProductRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Products.Select(p => p.Category).Distinct().OrderBy(p => p));
        }
    }
}

SportsStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.ViewModels;
using System.Linq;
namespace SportsStore.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private Cart cart;
        public CartController(IProductRepository repo, Cart cartServices)
        {
            repository = repo;
            cart = cartServices;
        }
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl });
        }
        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model Product
<div class="card card-body bg-light">
    <h3>
        <strong>@Model.Name</strong>
        <span class="float-right">
            @Model.Price.ToString("c")
        </span>
    </h3>
    <form id="@Model.ProductId" asp-action="AddToCart" asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="lead">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm float-right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

SportsStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="~/lib/twitter-bootstrap/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: navy;
            background-color: #fee;
        }
    </style>
    <script asp-src-include="~/lib/jquery/**/jquery.min.js"></script>
    <script asp-src-include="~/lib/jquery-validate/**/jquery.validate.min.js"></script>
    <script asp-src-include="~/lib/jquery-validation-unobtrusive/**/*.min.js"></script>
</head>
<body class="card">
    <div class="card-header">
        <h4>
            @ViewBag.Title
            <a class="btn btn-sm btn-primary float-right" asp-action="Logout" asp-controller="Account">Log Out</a>
        </h4>
    </div>
    <div class="card-body">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="~/lib/twitter-bootstrap/css/*.min.css" />
    <link rel="stylesheet" asp-href-include="~/lib/font-awesome/css/*.css" />
    <title>SportsStore</title>
</head>
<body>
    <div class="navbar navbar-expand-sm bg-dark navbar-dark" role="navigation">
        <a class="navbar-light" href="#">Sports Store</a>
        <div class="float-right">
            @await Component.InvokeAsync("CartSummary")
        </div>
    </div>
    <div class="row">
        <div id="categories" class="col-xl-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-xl-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>